# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install --no-optional
  displayName: 'npm install'

- script: |
    npm install -g vsce
  displayName: 'install Visual Studio Code Extensions'

- script: |
    vsce package
  displayName: 'generate VSCode extension'

- task: CopyFiles@2
  inputs:
    contents: '*.vsix'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'drop'

#- script: |
#    vsce publish -p $VSCE_KEY
#  displayName: 'publish VSCode extension'
#  env:
#    VSCE_KEY: $(vscekey)
